### ISSUE TITLE
Long notes on mobile Devices

### ISSUE THREAD

**Issue by theabbie** [ritz078/raaga#116]
![Screenshot_20200922-223545_Chrome](https://user-images.githubusercontent.com/17960677/93914347-0a333700-fd24-11ea-96d4-590996c9c8f3.png)
While using raaga.io on mobile devices, we can't create long notes by holding a key.

**Comment by ritz078** [comment]
I think it's because `onMouseUp` and `onMouseDown` won't work on touch devices. Adding `onTouchStart` and `onTouchEnd` in the following HTML element should fix this. Will you like to open a PR ?

https://github.com/ritz078/raaga/blob/b9d3a18d6ea9e161ef9f5de49342cdb821a1084e/components/Piano/Piano.tsx#L92-L102

**Comment by theabbie** [comment]
@ritz078 I don't completely understand the code and I am afraid I might break it, simply replacing it with `onTouchStart` might not be the solution because they might have different stntax in some other part of code. I don't think I would open a PR.

**Comment by sruthiragupathy** [comment]
I would like to give it a try, shall i proceed?

**Comment by ritz078** [comment]
@sruthiragupathy please go ahead.

**Comment by ritz078** [comment]
fixed via #122
